/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main.java.TD2;

import main.java.TD2.Exercice1.Somme;

public class App {

    public void Exercie1_question1()
    {
        //Lambda pour 2 entiers
        Somme<Integer> somme1 = (x,y) -> x+y;

        //Lambda pour 2 doubles
        Somme<Double> somme2 = (x, y) -> x+y;

        //Lambda pour 2 longs
        Somme<Long> somme3 = (x, y) -> x+y;

        //Lambda pour 2 strings
        Somme<String> somme4 = (x,y) -> x+y;

        System.out.println(somme1.somme(1,2));
        System.out.println(somme2.somme(1.1,2.2));
        System.out.println(somme3.somme(1L,2L));
        System.out.println(somme4.somme("toto","titi"));
    }

    public String getGreeting() {
        return "Hello World!";
    }


    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
