/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main.java.TD2;

import main.java.TD2.Exercice1.Somme;
import main.java.TD2.Exercice1.ToString;

import java.util.List;
import java.util.function.Predicate;

public class App {

    public void Exercie1_question1()
    {
        //Lambda pour 2 entiers
        Somme<Integer> somme1 = (x,y) -> x+y;

        //Lambda pour 2 doubles
        Somme<Double> somme2 = (x, y) -> x+y;

        //Lambda pour 2 longs
        Somme<Long> somme3 = (x, y) -> x+y;

        //Lambda pour 2 strings
        Somme<String> somme4 = (x,y) -> x+y;

        System.out.println(somme1.somme(1,2));
        System.out.println(somme2.somme(1.1,2.2));
        System.out.println(somme3.somme(1L,2L));
        System.out.println(somme4.somme("toto","titi"));
    }

    public void Exercice1_Question2(){
        //Lambda pour liste de String
        List<String> l = List.of("Toto", "Titi");
        ToString<List<String>> liste = l1 -> {
            //Je récupère chaque item de liste est j'ajoute une virgule
            StringBuffer str = new StringBuffer();
            for(String i: l1)
            {
                str.append(i);
                str.append(",");
            }
            return str.toString();
        };
        System.out.println(liste.tranform(l));
    }

    public void Exercice2_Question1()
    {
        Predicate<Integer> taillePetite = x -> x < 100;
        Predicate<Integer> tailleGrande = x -> x > 200;
        Predicate<Integer> tailleIncorrecte = taillePetite.or(tailleGrande);
        Predicate<Integer> tailleCorrecte = tailleIncorrecte.negate();
    }

    public String getGreeting() {
        return "Hello World!";
    }


    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
